title       = "dbvar"
baseURL     = "https://dbvar-cli.tamnd.com/"
description = "A command line for dbvar."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/dbvar-cli"
